import os


SECRET_KEY = os.environ.get("SUPERSET_SECRET_KEY", "")
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = os.environ.get("SUPERSET_SESSION_COOKIE_SECURE", "false").lower() == "true"
PERMANENT_SESSION_LIFETIME = int(os.environ.get("SUPERSET_SESSION_LIFETIME", "1800"))
WELCOME_PAGE_LAST_TAB = "examples"
