FROM python:3.14-slim

ENV PYTHONUNBUFFERED=1
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

COPY images/dagster/requirements-user-code.txt requirements.txt

RUN pip install --upgrade pip && \
    pip install \
        -r requirements.txt && \
        rm requirements.txt

RUN mkdir -p $DAGSTER_HOME

COPY images/dagster/dagster.yaml images/dagster/workspace.yaml $DAGSTER_HOME

# Add code location code
WORKDIR /opt/dagster/app
COPY workdirs/dagster /opt/dagster/app

# Run dagster code server on port 4000
EXPOSE 4000

HEALTHCHECK --timeout=1s --start-period=3s --interval=3s --retries=20 CMD ["dagster", "api", "grpc-health-check", "-p", "4000"]

# CMD allows this to be overridden from run launchers or executors to execute runs and steps
CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-f", "/opt/dagster/app/definitions.py"]
